server:
  port: 8080
  mode: debug

mysql:
  host: localhost
  port: 3306
  username: oasys
  password: xxxxxxxxxxxxx
  database: oasys
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: localhost
  port: 6379
  password: "xxxxxxxxxxxxx"
  db: 0

jwt:
  secret: "xxxxxxxxxxxxx"
  expire: 86400  # 24小时

upload:
  save_path: ./uploads
  max_size: 50  # MB 